/**
 * Equivalence tests: verify the Cloudflare Worker produces the same responses
 * as the original FastAPI implementation.
 *
 * Snapshots in test/snapshots/fastapi-responses.json are generated by running
 * the real FastAPI app (via starlette TestClient) against the same fixture data.
 * Regenerate with: python test/generate_snapshots.py
 */

import { describe, it, expect, beforeAll } from "vitest";
import { env, SELF } from "cloudflare:test";
import { seedBucket } from "./fixtures";
import snapshots from "./snapshots/fastapi-responses.json";

const BASE = "http://localhost";

/**
 * Strip origin and archive prefix from URLs to normalize between
 * FastAPI (/archive-root/) and Worker (/archive/) paths.
 */
function normalizeUrl(url: string): string {
  return url.replace(/^https?:\/\/[^/]+\/archive(?:-root)?\//, "");
}

function normalizeBody(body: unknown): unknown {
  if (Array.isArray(body)) {
    return body.map(normalizeBody);
  }
  if (body !== null && typeof body === "object") {
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(body as Record<string, unknown>)) {
      if (k === "url" && typeof v === "string") {
        result[k] = normalizeUrl(v);
      } else {
        result[k] = normalizeBody(v);
      }
    }
    return result;
  }
  return body;
}

// ── Request catalog (same requests used by generate_snapshots.py) ──

interface RequestSpec {
  key: string;
  method: "GET" | "POST";
  path: string;
  body?: unknown;
}

const REQUEST_CATALOG: RequestSpec[] = [
  { key: "publicinfo", method: "GET", path: "/api/publicinfo" },

  { key: "update-ios-from-59.0", method: "POST", path: "/api/v1/update", body: { version: "59.0", platform: 1 } },
  { key: "update-ios-from-59.2", method: "POST", path: "/api/v1/update", body: { version: "59.2", platform: 1 } },
  { key: "update-ios-at-latest", method: "POST", path: "/api/v1/update", body: { version: "59.4", platform: 1 } },
  {
    key: "update-android-from-59.0",
    method: "POST",
    path: "/api/v1/update",
    body: { version: "59.0", platform: 2 },
  },

  { key: "batch-ios-type0", method: "POST", path: "/api/v1/batch", body: { package_type: 0, platform: 1, exclude: [] } },
  {
    key: "batch-ios-type0-exclude2",
    method: "POST",
    path: "/api/v1/batch",
    body: { package_type: 0, platform: 1, exclude: [2] },
  },
  {
    key: "batch-ios-type3-notfound",
    method: "POST",
    path: "/api/v1/batch",
    body: { package_type: 3, platform: 1, exclude: [] },
  },
  {
    key: "batch-ios-no-exclude-field",
    method: "POST",
    path: "/api/v1/batch",
    body: { package_type: 0, platform: 1 },
  },

  {
    key: "download-ios-0-2",
    method: "POST",
    path: "/api/v1/download",
    body: { package_type: 0, package_id: 2, platform: 1 },
  },
  {
    key: "download-ios-0-999-notfound",
    method: "POST",
    path: "/api/v1/download",
    body: { package_type: 0, package_id: 999, platform: 1 },
  },
  {
    key: "download-android-0-1",
    method: "POST",
    path: "/api/v1/download",
    body: { package_type: 0, package_id: 1, platform: 2 },
  },

  { key: "getdb-testdb", method: "GET", path: "/api/v1/getdb/testdb" },
  { key: "getdb-notfound", method: "GET", path: "/api/v1/getdb/nonexistent" },
  { key: "getdb-sanitize", method: "GET", path: "/api/v1/getdb/test..db" },

  { key: "getfile-single", method: "POST", path: "/api/v1/getfile", body: { files: ["some/file.txt"], platform: 1 } },
  {
    key: "getfile-multi",
    method: "POST",
    path: "/api/v1/getfile",
    body: { files: ["some/file.txt", "another/asset.png"], platform: 1 },
  },
  {
    key: "getfile-unknown",
    method: "POST",
    path: "/api/v1/getfile",
    body: { files: ["nonexistent/file.bin"], platform: 1 },
  },
  {
    key: "getfile-traversal",
    method: "POST",
    path: "/api/v1/getfile",
    body: { files: ["../some/file.txt"], platform: 1 },
  },

  { key: "release-info", method: "GET", path: "/api/v1/release_info" },
];

// Type for snapshot entries
interface SnapshotEntry {
  status: number;
  body?: unknown;
  body_base64?: string;
  content_type?: string;
  content_disposition?: string;
}

beforeAll(async () => {
  await seedBucket(env.ARCHIVE_BUCKET);
});

describe("Equivalence with FastAPI implementation", () => {
  for (const req of REQUEST_CATALOG) {
    const expected = (snapshots as Record<string, SnapshotEntry>)[req.key];
    if (!expected) {
      it.skip(`${req.key} - no snapshot found`, () => {});
      continue;
    }

    it(`${req.key}`, async () => {
      const fetchOptions: RequestInit = { method: req.method };
      if (req.body !== undefined) {
        fetchOptions.headers = { "Content-Type": "application/json" };
        fetchOptions.body = JSON.stringify(req.body);
      }

      const res = await SELF.fetch(`${BASE}${req.path}`, fetchOptions);

      // Compare status code
      expect(res.status).toBe(expected.status);

      if (expected.body_base64 !== undefined) {
        // Binary response comparison
        const buf = await res.arrayBuffer();
        const actual = btoa(String.fromCharCode(...new Uint8Array(buf)));
        expect(actual).toBe(expected.body_base64);

        if (expected.content_type) {
          expect(res.headers.get("Content-Type")).toBe(expected.content_type);
        }
        if (expected.content_disposition) {
          expect(res.headers.get("Content-Disposition")).toBe(expected.content_disposition);
        }
      } else if (expected.body !== undefined) {
        // JSON response comparison
        const actualBody = await res.json();
        let normalizedActual = normalizeBody(actualBody);

        // For publicinfo, normalize the application field to match snapshot
        if (req.key === "publicinfo" && typeof normalizedActual === "object" && normalizedActual !== null) {
          const info = normalizedActual as Record<string, unknown>;
          const app = info.application as Record<string, string> | undefined;
          if (app) {
            info.application = {
              NPPS4DLAPIVersion: app.NPPS4DLAPIVersion ?? "",
            };
          }
          normalizedActual = info;
        }

        expect(normalizedActual).toEqual(expected.body);
      }
    });
  }
});
